### ISSUE TITLE
Example of most basic usage, unable to apply styles

### ISSUE THREAD

**Issue by peduarte** [rebassjs/components#10]
Hey,

I was wondering if anyone could help me understand why this super basic example is not working?

Code Sandbox link: https://codesandbox.io/s/mjvrlvvw4y

```js
import system from "@rebass/components";

const Title = system({
  p: 5
});

function App() {
  return <Title>Hello, world!</Title>;
}
```

I am aware I can pass extra arguments, and indeed if I pass `space` as a second argument, it works. Is this by design?

**Comment by lucastobrazil** [comment]
Yes, you need to add `space` 

```js
const Title = system(
  {
    p: 5
  },
  "space"
);
```
Agreed it would be nicer if the `system` function would automatically add the associated style function if it's set in the default props object (first argument). But after using it for a while, I kinda like that it forces you to really think about the 'api' the component exposes. 

That said, the whole array of strings as a second argument feels a bit weird to me. I'd almost prefer to have like:

```js
import { space, color } from 'styled-system';

const Title = system(
  defaultProps: {
    p: 5
  },
  props: {
   space, 
   color
  }
);
```

Feels a little more declarative?

**Comment by flybayer** [comment]
Nice @lucastobrazil, I really like that idea

**Comment by peduarte** [comment]
Oh right, I see.

So if the additional arguments are required, does this mean the following code wouldn't work?

```js
const Heading = system({
  is: 'h2',
  m: 0,
  fontSize: 6
})
```

Code snippet was taken from [the docs](https://github.com/rebassjs/components#changing-the-underlying-html-element)

**Comment by lucastobrazil** [comment]
Yes I believe so, this would not work. That snippet in the docs seems to be focused on the `is` prop, so maybe the author left out the style function strings. Would probably be good to change that though.

**Comment by peduarte** [comment]
Yeah, I think that's what confused me. Also, coming from `system-components` where exposing the API wasn't required.

Anyway, thanks @lucastobrazil 👊
