### ISSUE TITLE
Wrong inheritance from rebass component

### ISSUE THREAD

**Issue by Kikobeats** [rebassjs/components#14]
Hello,

I'm migrating from `rebass@2` and `styled-system` to `rebass@3` and `rebass/components`.

Because `rebass/components` implementation is not exactly `styled-system` I found a piece of code that is working fine in the old setup but no under the new stack.

The thing that I'm trying to achieve is pretty simple: Just I want to extend `Flex` component from `rebass` to accept more props values:

```jsx
import system from '@rebass/components'
import { Flex as FlexBase } from 'rebass'

const Flex = system(
  { tag: FlexBase },
  'alignContent',
  'justifyContent',
  'flexDirection',
  'alignItems',
  'flexWrap',
  'maxWidth',
  'lineHeight',
  'borderRadius',
  'boxShadow'
)

Flex.displayName = 'Flex'

export default Flex
```

The thing I noted is the new component is not inheritance the base (Flex) component properly.

Specifically, the new component doesn't have the inheritance of the `componentStyle` from the base component.

![screenshot 2018-11-25 at 13 30 53](https://user-images.githubusercontent.com/2096101/48979106-61c7d380-f0b6-11e8-9d2d-e5496d0ccea8.png)

I understand this could be an speficif internal related with styled-components, but actually I have no idea.

This is happening because under `@rebass/components` the implementation to determinate the `tag` component is using [forwardRef](https://github.com/rebassjs/components/blob/master/src/index.js#L57) and it's a bit smarter than the [original implementation](https://github.com/jxnblk/styled-system/blob/master/packages/system-components/src/System.js#L84) that is using a simple styled-components constructor.

Although looks it's not working properly as I expected, I suppose the approach of use this new implementation have advantages in terms of perfomance, so I'm interested why this change.

Feel it's related with https://github.com/styled-components/styled-components/issues/1209

**Comment by Kikobeats** [comment]
Based on the styled-components issue conversation I made a modification in the original code for merging `componentStyle.rules` that in fact they are the rules used for supporting prop values:

```jsx
// this function is the same but Base is injected
const tag = Base =>
  React.forwardRef(({ blacklist = [], ...props }, ref) => {
    // console.log('Bse', Base.componentStyle.rules)
    const next = omit(
      props,
      typeof Base === 'string' ? [..._blacklist, ...blacklist] : ['extend']
    )

    return React.createElement(Base, { ...next, ref })
  })

const getPropTypes = funcs =>
  funcs
    .filter(fn => typeof fn === 'function' && typeof fn.propTypes === 'object')
    .reduce(
      (a, fn) => ({
        ...a,
        ...fn.propTypes
      }),
      {}
    )

const system = (props = {}, ...keysOrStyles) => {
  // getting Base out of `tag` function for merging rules
  const Base = props.extend || props.tag || props.is || 'div'
  const funcs = keysOrStyles.map(key => styles[key] || key)
  const Component = styled(tag(Base))([], ...funcs, css)

  // merging rules smart algorithm lol
  Component.componentStyle.rules = [
    ...Component.componentStyle.rules,
    ...Base.componentStyle.rules
  ].reduce((acc, item) => {
    const index = acc.findIndex(i => i.toString() === item.toString())
    return index === -1 ? [...acc, item] : item
  }, [])

  const baseProps = util.get(props, 'extend.defaultProps') || {}
  Component.defaultProps = { ...baseProps, ...props }
  Component.propTypes = getPropTypes(funcs)
  Component.systemComponent = true
  return Component
}
```

**Comment by jxnblk** [comment]
I'll have to look into this a little later, but for Rebass v3, I'd *highly* recommend extending the components using styled-components directly, e.g. `const CustomFlex = styled(Flex)(maxWidth)`

**Comment by Kikobeats** [comment]
yup, although the merging algorithm is basically doing that but sugar syntactic
