### ISSUE TITLE
@rebass/components is not compatible with emotion 10

### ISSUE THREAD

**Issue by vospascal** [rebassjs/components#18]
@rebass/components is not compatible with emotion 10

**Comment by vospascal** [comment]
Uncaught Error: The package "react-emotion" has been replaced by "@emotion/styled" in version 10. See https://emotion.sh/docs/migrating-to-emotion-10 for more information on migrating.

**Comment by macklinu** [comment]
Is the solution similar to https://github.com/rebassjs/rebass/pull/537, where the Babel config would need to be updated to change the package `@rebass/components` imports from (e.g. replacing `react-emotion` with `@emotion/styled`?

https://github.com/rebassjs/components/blob/ca2f0a2e21797410b407c9c8b87c1e855d433472/.babelrc#L14

**Comment by jxnblk** [comment]
I believe that's all that's needed, though this probably warrants a major version bump

**Comment by vospascal** [comment]
ended up with making them from styled-system this removes the dependency problem.. i did 

import styled from '@emotion/styled';
import {
  alignItems,
  alignSelf,
  color, display,
  flex,
  flexBasis,
  fontSize,
  justifyContent,
  order,
  space,
  width,
} from 'styled-system';

export const Box = styled('div')({
  boxSizing: 'border-box',
}, width, space, flex, fontSize, color, order, alignItems, justifyContent, alignSelf, flexBasis, display, (props) => props.css);
Box.displayName = 'Box';
