### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by mrozbarry** [rebassjs/components#20]
Thanks for building @rebass/components, it has cleaned up a lot of code in a project my team is working on.

My only concern is that the current status is pre-release, with no roadmap or indication on the stability of the code's current state. I was curious is there is any insight/discussion on what will make this a stable release, and when that can be expected.

**Comment by MANTENN** [comment]
I checked out the release changes in styles-system V4, and V5 the api has changed significantly after trying to update the dependencies.

@jxnblk What's the plan?

**Comment by MANTENN** [comment]
After further digging: https://github.com/styled-system/styled-system/commits/master?after=19b815b2e93f0bea28124299250e3e514f402e4e+139&path%5B%5D=packages

Looks like this is going to be deprecated once all the features are added into the styled system.
