### ISSUE TITLE
Remove `is` prop in favor of styled-components `as` prop

### ISSUE THREAD

**Issue by jxnblk** [rebassjs/components#3]
Will wait until it's officially released, of course

**Comment by tadeuszwojcik** [comment]
Do you plan migrating from `extend` & `is` to `as` prop? or `extend` will stay?

**Comment by jxnblk** [comment]
It depends on how the `as` prop is implemented in each library and will need to test it.

E.g. if it's possible to replace this functionality with the `as` prop, then there's no need for `extend`:

```js
const Box = styled('div')(color)
const Flex = styled(Box)()

// if this works, the extend prop isn't needed
// <Flex as='footer' color='blue' />
```
