### ISSUE TITLE
blacklist is ignored when component is 'extend'ed

### ISSUE THREAD

**Issue by purge** [rebassjs/components#5]
```
system({
  blacklist:['whatever']
});
```

vs

```
system({
  extend: Something,
  blacklist:['whatever']
});

**Comment by alexlouden** [comment]
I've noticed the same thing - reproduced it here: https://codesandbox.io/s/j43vv5w2k9

```html
<div class="sc-bdVaJa jZblEN" p="5">
    <button class="sc-jtRfpW kBOnIP">Boop</button>
    <button class="sc-jtRfpW cTvhTf" uppercase="true">Boop</button>
</div>
```

**Comment by lucastobrazil** [comment]
@alexlouden @purge I noticed it too! and  also that you cannot merge the blacklist of the original component with the one extending it. Anyone interested in opening a PR for this? I can start but i'd need someone else for sanity :)

**Comment by cneeson** [comment]
Bump on this, I'd be happy to chip in on a PR @lucastobrazil 
Edit: Added a PR below, if anyone gets a chance, feel free to review

**Comment by lucastobrazil** [comment]
This is most excellent @cneeson - thanks for doing it! 

Commented on the PR, would be great to have it merged. I created a small PR that can come after that which documents the blacklist property and extending it (https://github.com/rebassjs/components/pull/21)
