### ISSUE TITLE
Getting render errors when trying this library

### ISSUE THREAD

**Issue by eddiewang** [rebassjs/components#7]
I'm getting a slew of styled-component errors when I try to render a component created the the system-component helper.

The top level error is:
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

Here are the rest of the errors:
![image](https://user-images.githubusercontent.com/2057997/46693400-aa473280-cbd7-11e8-9dc2-768fb539fd9e.png)

I should also mention that i I create a styled component from scratch like so:

```js
const Text = styled.div`
  color: ${props => props.theme.colors.silver};
`
```

it works just fine.

Here is the output when I render the component created from system-component `console.lo('ext', <Text />)`

![image](https://user-images.githubusercontent.com/2057997/46695124-b1bd0a80-cbdc-11e8-8ff5-4cb54f7a40bf.png)

Any tips would be greatly appreciate. Thanks for a great library!

**Comment by jxnblk** [comment]
Thanks! Could you include a code snippet of how you're using `@rebass/components`?

**Comment by eddiewang** [comment]
@jxnblk here's the code snippet:

```js
import * as React from 'react'
import system from '@rebass/components'

export const Text = system(
  {
    is: 'p',
    fontSize: 2,
    color: 'near-black',
    fontFamily: 'sansSerif'
  },
  'space',
  'width',
  'textAlign',
  'lineHeight',
  'fontWeight',
  'letterSpacing'
)

console.log('ext', <Text />)
```

Here's where I import it:
```js
import * as React from 'react'
import { Layout, Menu } from 'antd'
import styled from 'styled-components'
import { Text } from '../../components/atoms'

// const Text = styled.div`
//   color: blue;
// `

const { Sider, Content } = Layout
const { SubMenu } = Menu

class MainView extends React.Component {
  render() {
    return (
      <Layout style={{ minHeight: '100vh' }}>
        <Sider theme="light">
          <Menu theme="light" mode="inline">
            <SubMenu key="/wallet" title={<Text>la</Text>}>
              <Menu.Item key="/wallet/activity">Activity</Menu.Item>
              <Menu.Item key="/wallet/transact">Transact</Menu.Item>
              <Menu.Item key="/wallet/settings">Settings</Menu.Item>
            </SubMenu>
          </Menu>
        </Sider>
        <Layout>
          <Content>Hello World</Content>
        </Layout>
      </Layout>
    )
  }
}

export default MainView
```

You can see in the commented out component - that's the component I substituted with and worked.

**Comment by eddiewang** [comment]
@jxnblk figured it out this morning! I peeked into my package.json and realized that while I did upgrade the `react` library to the latest version, `react-dom` was still on v16.0. I upgraded that to @latest and it's now rendering properly! Excited to use this library.
