### ISSUE TITLE
Using a component with `is` results in a react warning

### ISSUE THREAD

**Issue by ferdinandsalis** [rebassjs/components#8]
Currently when doing something like this where `Link` is a system component,
```js
import { Link as AppLink } from '@reach/router'

<Link is={AppLink}>Some Link</Link>
```
it will show this warning 
```
Received a `object` for a string attribute `is`. If this is expected, cast the value to a string.
```

Is this the expected behaviour?

**Comment by MANTENN** [comment]
"Is" is meant for changing the underlying html element, in that case it only accepts a string. Reasoning from this, it's the expected behavior. 

To extend you'd use "extend". Visit https://github.com/rebassjs/components#extending-components for more info.
